version: "3.7"

services:
  vscode:
    build: .
    image: kbuley/jsdevcontainer
    volumes:
      # Docker volume to contain node_modules for performance reason
      - node_modules:/workspace/node_modules
      - ../:/workspace
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/root/.ssh:z
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Git config
      - ~/.gitconfig:/root/.gitconfig:z
    environment:
      - TZ=
    entrypoint: zsh -c "while sleep 1000; do :; done"
    ports:
      - 3000/tcp

volumes:
  node_modules:
